# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- azure-pipelines

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: NuGetToolInstaller@1

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: "Set Hidi's version-number"
  inputs:
    targetType: 'inline'
    script: |
         $xml = [Xml] (Get-Content .\src\Microsoft.OpenApi.Hidi\Microsoft.OpenApi.Hidi.csproj)
         $version = $xml.Project.PropertyGroup.Version
         echo $version
         echo "##vso[task.setvariable variable=version]$version"        
      
# - task: MSBuild@1
#   displayName: 'Pack OpenApi Hidi'
#   inputs:
#     solution: src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
#     configuration: Release
#     msbuildArguments: '/t:publish /p:OutputPath=$(Build.ArtifactStagingDirectory)\Microsoft.OpenApi.Hidi-v$(version) /p:RuntimeIdentifier=win-x64 /p:PublishSingleFile=true /p:SelfContained=true /p:PublishTrimmed=true'
#     # msbuild: /t:publish /p:TargetFramework=net5.0 /p:SelfContained=true /p:PublishTrimmed=True /p:PublishReadyToRun=True /p:RuntimeIdentifier=win-x86  -p:PublishSingleFile=true

# - task: ManifestGeneratorTask@0
#   inputs:
#     ManifestDirPath: "$(System.DefaultWorkingDirectory)/_manifest"
#     BuildComponentPath: "$(System.DefaultWorkingDirectory)/build"
#     PackageName: "graph-explorer-v2"
#     PackageVersion: "$(Build.UpdateBuildNumber)"

- task: MSBuild@1
  displayName: 'Pack OpenApi Hidi'
  inputs:
    solution: src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
    configuration: Release
    msbuildArguments: '/t:pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/Nugets /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: -c Release --runtime win-x64 -p:PublishSingleFile=true --self-contained true --output $(Build.ArtifactStagingDirectory) -p:PublishTrimmed=true
    projects: 'src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj'
    publishWebProjects: False
    zipAfterPublish: false


# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\Application'
#   inputs:
#     Contents: |
#       $(Build.ArtifactStagingDirectory)\Github\Microsoft.OpenApi.Hidi-v$(version)\**\*.exe
#     SourceFolder: '$(Build.ArtifactStagingDirectory)\Github' 
#     TargetFolder: '$(Build.ArtifactStagingDirectory)\Application'

- task: PublishBuildArtifacts@1
  displayName: 'Package Hidi'
  inputs: 
    ArtifactName: Nugets  
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Nugets'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Hidi'
  inputs: 
    ArtifactName: Microsoft.OpenApi.Hidi-v$(version)  
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
     
